name: stern_brocot
description: Stern-Brocot generates all positive rational numbers.
version: 1.0.0
repository: https://github.com/TheMaverickProgrammer/stern_brocot

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
